// <auto-generated />
namespace Newaz_1271713_Code_First.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OrderInitialWithSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderInitialWithSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "202305280640520_OrderInitialWithSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
